# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceGrafica.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1092, 770)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboEPSG_from = QtWidgets.QComboBox(self.tab)
        self.comboEPSG_from.setGeometry(QtCore.QRect(30, 140, 301, 22))
        self.comboEPSG_from.setObjectName("comboEPSG_from")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_from.addItem("")
        self.comboEPSG_to = QtWidgets.QComboBox(self.tab)
        self.comboEPSG_to.setGeometry(QtCore.QRect(460, 140, 301, 22))
        self.comboEPSG_to.setObjectName("comboEPSG_to")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.comboEPSG_to.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 79, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineOpen = QtWidgets.QLineEdit(self.tab)
        self.lineOpen.setGeometry(QtCore.QRect(160, 50, 581, 20))
        self.lineOpen.setObjectName("lineOpen")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(90, 110, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(500, 110, 151, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(30, 190, 781, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineY = QtWidgets.QLineEdit(self.tab)
        self.lineY.setGeometry(QtCore.QRect(40, 240, 221, 20))
        self.lineY.setObjectName("lineY")
        self.lineX = QtWidgets.QLineEdit(self.tab)
        self.lineX.setGeometry(QtCore.QRect(320, 240, 221, 20))
        self.lineX.setObjectName("lineX")
        self.calculaButton = QtWidgets.QPushButton(self.tab)
        self.calculaButton.setGeometry(QtCore.QRect(610, 240, 131, 24))
        self.calculaButton.setObjectName("calculaButton")
        self.lineResult = QtWidgets.QLineEdit(self.tab)
        self.lineResult.setGeometry(QtCore.QRect(70, 280, 421, 20))
        self.lineResult.setObjectName("lineResult")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(20, 310, 781, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 600, 611, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(90, 210, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(340, 210, 81, 16))
        self.label_5.setObjectName("label_5")
        self.invertButton = QtWidgets.QPushButton(self.tab)
        self.invertButton.setGeometry(QtCore.QRect(610, 280, 131, 24))
        self.invertButton.setObjectName("invertButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_dadosBrutos = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_dadosBrutos.setGeometry(QtCore.QRect(50, 83, 751, 267))
        self.tableWidget_dadosBrutos.setObjectName("tableWidget_dadosBrutos")
        self.tableWidget_dadosBrutos.setColumnCount(7)
        self.tableWidget_dadosBrutos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos.setHorizontalHeaderItem(6, item)
        self.tableWidget_dadosBrutos.horizontalHeader().setStretchLastSection(True)
        self.pushButton_openstation = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_openstation.setGeometry(QtCore.QRect(40, 20, 85, 30))
        self.pushButton_openstation.setObjectName("pushButton_openstation")
        self.pushButton_Recalcula = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Recalcula.setGeometry(QtCore.QRect(190, 640, 85, 30))
        self.pushButton_Recalcula.setObjectName("pushButton_Recalcula")
        self.pushButton_plota_pontos = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_plota_pontos.setGeometry(QtCore.QRect(280, 640, 101, 30))
        self.pushButton_plota_pontos.setObjectName("pushButton_plota_pontos")
        self.tableWidget_coordenadasFinais = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_coordenadasFinais.setGeometry(QtCore.QRect(48, 388, 599, 247))
        self.tableWidget_coordenadasFinais.setObjectName("tableWidget_coordenadasFinais")
        self.tableWidget_coordenadasFinais.setColumnCount(5)
        self.tableWidget_coordenadasFinais.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_coordenadasFinais.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_coordenadasFinais.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_coordenadasFinais.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_coordenadasFinais.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_coordenadasFinais.setHorizontalHeaderItem(4, item)
        self.pushButton_salvarCoordenadas = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_salvarCoordenadas.setGeometry(QtCore.QRect(390, 640, 151, 30))
        self.pushButton_salvarCoordenadas.setObjectName("pushButton_salvarCoordenadas")
        self.lineEditEstacao_N = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditEstacao_N.setGeometry(QtCore.QRect(758, 448, 113, 28))
        self.lineEditEstacao_N.setObjectName("lineEditEstacao_N")
        self.lineEditEstacao_E = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditEstacao_E.setGeometry(QtCore.QRect(758, 488, 113, 28))
        self.lineEditEstacao_E.setObjectName("lineEditEstacao_E")
        self.lineEditEstacao_H = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditEstacao_H.setGeometry(QtCore.QRect(758, 528, 113, 28))
        self.lineEditEstacao_H.setObjectName("lineEditEstacao_H")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(738, 458, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(738, 498, 16, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(738, 538, 16, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(778, 428, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(948, 428, 58, 14))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(908, 458, 16, 16))
        self.label_11.setObjectName("label_11")
        self.lineEditRe_H = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditRe_H.setGeometry(QtCore.QRect(928, 528, 113, 28))
        self.lineEditRe_H.setObjectName("lineEditRe_H")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(908, 498, 16, 16))
        self.label_12.setObjectName("label_12")
        self.lineEditRe_E = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditRe_E.setGeometry(QtCore.QRect(928, 488, 113, 28))
        self.lineEditRe_E.setObjectName("lineEditRe_E")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(928, 448, 113, 28))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(908, 538, 16, 16))
        self.label_13.setObjectName("label_13")
        self.pushButtonCalculaAzimute = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonCalculaAzimute.setGeometry(QtCore.QRect(730, 670, 121, 30))
        self.pushButtonCalculaAzimute.setObjectName("pushButtonCalculaAzimute")
        self.lineEditAzimute = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditAzimute.setGeometry(QtCore.QRect(728, 630, 221, 28))
        self.lineEditAzimute.setObjectName("lineEditAzimute")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(330, 30, 351, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(192, 361, 411, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(730, 600, 121, 16))
        self.label_16.setObjectName("label_16")
        self.pushButton_exportar_dxf = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_exportar_dxf.setGeometry(QtCore.QRect(550, 640, 85, 30))
        self.pushButton_exportar_dxf.setObjectName("pushButton_exportar_dxf")
        self.pushButton_Teste = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Teste.setGeometry(QtCore.QRect(620, 680, 85, 30))
        self.pushButton_Teste.setObjectName("pushButton_Teste")
        self.groupBoxXYouXYZ = QtWidgets.QGroupBox(self.tab_2)
        self.groupBoxXYouXYZ.setGeometry(QtCore.QRect(840, 10, 185, 51))
        self.groupBoxXYouXYZ.setObjectName("groupBoxXYouXYZ")
        self.radioButton2D = QtWidgets.QRadioButton(self.groupBoxXYouXYZ)
        self.radioButton2D.setGeometry(QtCore.QRect(22, 30, 55, 20))
        self.radioButton2D.setObjectName("radioButton2D")
        self.radioButton3D = QtWidgets.QRadioButton(self.groupBoxXYouXYZ)
        self.radioButton3D.setGeometry(QtCore.QRect(100, 30, 53, 20))
        self.radioButton3D.setObjectName("radioButton3D")
        self.checkBoxCamadaMuro = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxCamadaMuro.setGeometry(QtCore.QRect(820, 330, 117, 20))
        self.checkBoxCamadaMuro.setObjectName("checkBoxCamadaMuro")
        self.checkBoxCamadaCota = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxCamadaCota.setGeometry(QtCore.QRect(820, 370, 119, 20))
        self.checkBoxCamadaCota.setObjectName("checkBoxCamadaCota")
        self.lineEditCamadaMuro = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditCamadaMuro.setGeometry(QtCore.QRect(936, 326, 113, 28))
        self.lineEditCamadaMuro.setObjectName("lineEditCamadaMuro")
        self.lineEditCamadaCota = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditCamadaCota.setGeometry(QtCore.QRect(936, 364, 113, 28))
        self.lineEditCamadaCota.setObjectName("lineEditCamadaCota")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(50, 690, 611, 16))
        self.label_26.setObjectName("label_26")
        self.groupBoxQualoTipo = QtWidgets.QGroupBox(self.tab_2)
        self.groupBoxQualoTipo.setGeometry(QtCore.QRect(840, 80, 179, 93))
        self.groupBoxQualoTipo.setObjectName("groupBoxQualoTipo")
        self.radioButtonTopografica = QtWidgets.QRadioButton(self.groupBoxQualoTipo)
        self.radioButtonTopografica.setGeometry(QtCore.QRect(18, 30, 103, 20))
        self.radioButtonTopografica.setObjectName("radioButtonTopografica")
        self.radioButtonUTM = QtWidgets.QRadioButton(self.groupBoxQualoTipo)
        self.radioButtonUTM.setGeometry(QtCore.QRect(18, 58, 103, 20))
        self.radioButtonUTM.setObjectName("radioButtonUTM")
        self.groupBoxQualoTipo_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBoxQualoTipo_2.setGeometry(QtCore.QRect(850, 182, 179, 131))
        self.groupBoxQualoTipo_2.setObjectName("groupBoxQualoTipo_2")
        self.radioButtonTopografica_2 = QtWidgets.QRadioButton(self.groupBoxQualoTipo_2)
        self.radioButtonTopografica_2.setGeometry(QtCore.QRect(19, 30, 103, 20))
        self.radioButtonTopografica_2.setObjectName("radioButtonTopografica_2")
        self.radioButtonUTM_2 = QtWidgets.QRadioButton(self.groupBoxQualoTipo_2)
        self.radioButtonUTM_2.setGeometry(QtCore.QRect(19, 60, 103, 20))
        self.radioButtonUTM_2.setObjectName("radioButtonUTM_2")
        self.radioButtonUTM_3 = QtWidgets.QRadioButton(self.groupBoxQualoTipo_2)
        self.radioButtonUTM_3.setGeometry(QtCore.QRect(20, 90, 103, 20))
        self.radioButtonUTM_3.setObjectName("radioButtonUTM_3")
        self.pushButton_Virgual_Ponto_Change = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Virgual_Ponto_Change.setGeometry(QtCore.QRect(990, 570, 21, 27))
        self.pushButton_Virgual_Ponto_Change.setObjectName("pushButton_Virgual_Ponto_Change")
        self.label_Caminho_Arquivo_M21 = QtWidgets.QLabel(self.tab_2)
        self.label_Caminho_Arquivo_M21.setGeometry(QtCore.QRect(80, 60, 711, 17))
        self.label_Caminho_Arquivo_M21.setText("")
        self.label_Caminho_Arquivo_M21.setObjectName("label_Caminho_Arquivo_M21")
        self.pushButton_Coordenada_Estacao = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Coordenada_Estacao.setGeometry(QtCore.QRect(1020, 570, 21, 27))
        self.pushButton_Coordenada_Estacao.setObjectName("pushButton_Coordenada_Estacao")
        self.pushButton_SalvaCoordenadaEstacao = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_SalvaCoordenadaEstacao.setGeometry(QtCore.QRect(960, 570, 21, 27))
        self.pushButton_SalvaCoordenadaEstacao.setObjectName("pushButton_SalvaCoordenadaEstacao")
        self.pushButton_DX_teste = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_DX_teste.setGeometry(QtCore.QRect(930, 570, 21, 27))
        self.pushButton_DX_teste.setObjectName("pushButton_DX_teste")
        self.pushButton_RecalculaPor2pontos = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_RecalculaPor2pontos.setGeometry(QtCore.QRect(64, 640, 121, 30))
        self.pushButton_RecalculaPor2pontos.setObjectName("pushButton_RecalculaPor2pontos")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_abrir_Conexao = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_abrir_Conexao.setGeometry(QtCore.QRect(158, 340, 113, 30))
        self.pushButton_abrir_Conexao.setObjectName("pushButton_abrir_Conexao")
        self.lineEdit_Porta = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_Porta.setGeometry(QtCore.QRect(150, 90, 131, 28))
        self.lineEdit_Porta.setObjectName("lineEdit_Porta")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(88, 96, 58, 14))
        self.label_17.setObjectName("label_17")
        self.lineEdit_bits_por_segundo = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_bits_por_segundo.setGeometry(QtCore.QRect(150, 130, 131, 28))
        self.lineEdit_bits_por_segundo.setObjectName("lineEdit_bits_por_segundo")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(36, 134, 111, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_tamanho_do_dado = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_tamanho_do_dado.setGeometry(QtCore.QRect(150, 168, 131, 28))
        self.lineEdit_tamanho_do_dado.setObjectName("lineEdit_tamanho_do_dado")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(28, 172, 119, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(74, 212, 69, 20))
        self.label_20.setObjectName("label_20")
        self.lineEdit_paridade = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_paridade.setGeometry(QtCore.QRect(150, 208, 131, 28))
        self.lineEdit_paridade.setObjectName("lineEdit_paridade")
        self.lineEdit_bits_de_parada = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_bits_de_parada.setGeometry(QtCore.QRect(150, 244, 131, 28))
        self.lineEdit_bits_de_parada.setObjectName("lineEdit_bits_de_parada")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(40, 248, 99, 20))
        self.label_21.setObjectName("label_21")
        self.lineEdit_controle_de_fluxo = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_controle_de_fluxo.setGeometry(QtCore.QRect(150, 284, 131, 28))
        self.lineEdit_controle_de_fluxo.setText("")
        self.lineEdit_controle_de_fluxo.setObjectName("lineEdit_controle_de_fluxo")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(24, 288, 115, 20))
        self.label_22.setObjectName("label_22")
        self.label_status_conexao = QtWidgets.QLabel(self.tab_4)
        self.label_status_conexao.setGeometry(QtCore.QRect(44, 442, 225, 16))
        self.label_status_conexao.setObjectName("label_status_conexao")
        self.pushButton_localizaPorta = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_localizaPorta.setGeometry(QtCore.QRect(356, 94, 127, 30))
        self.pushButton_localizaPorta.setObjectName("pushButton_localizaPorta")
        self.lineEdit_portaEncontrada = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_portaEncontrada.setGeometry(QtCore.QRect(494, 94, 189, 28))
        self.lineEdit_portaEncontrada.setObjectName("lineEdit_portaEncontrada")
        self.tabWidget.addTab(self.tab_4, "")
        self.ponto2dxf = QtWidgets.QWidget()
        self.ponto2dxf.setObjectName("ponto2dxf")
        self.pushButton_pontos2dxf = QtWidgets.QPushButton(self.ponto2dxf)
        self.pushButton_pontos2dxf.setGeometry(QtCore.QRect(130, 60, 85, 30))
        self.pushButton_pontos2dxf.setObjectName("pushButton_pontos2dxf")
        self.label_23 = QtWidgets.QLabel(self.ponto2dxf)
        self.label_23.setGeometry(QtCore.QRect(360, 60, 411, 16))
        self.label_23.setObjectName("label_23")
        self.tableWidget_dadosBrutos_2 = QtWidgets.QTableWidget(self.ponto2dxf)
        self.tableWidget_dadosBrutos_2.setGeometry(QtCore.QRect(216, 190, 637, 267))
        self.tableWidget_dadosBrutos_2.setMinimumSize(QtCore.QSize(637, 0))
        self.tableWidget_dadosBrutos_2.setObjectName("tableWidget_dadosBrutos_2")
        self.tableWidget_dadosBrutos_2.setColumnCount(5)
        self.tableWidget_dadosBrutos_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dadosBrutos_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_dadosBrutos_2.horizontalHeader().setStretchLastSection(True)
        self.lineEdit_padrao = QtWidgets.QLineEdit(self.ponto2dxf)
        self.lineEdit_padrao.setGeometry(QtCore.QRect(330, 130, 401, 20))
        self.lineEdit_padrao.setObjectName("lineEdit_padrao")
        self.label_24 = QtWidgets.QLabel(self.ponto2dxf)
        self.label_24.setGeometry(QtCore.QRect(260, 130, 61, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_separador = QtWidgets.QLineEdit(self.ponto2dxf)
        self.lineEdit_separador.setGeometry(QtCore.QRect(330, 160, 61, 20))
        self.lineEdit_separador.setObjectName("lineEdit_separador")
        self.label_25 = QtWidgets.QLabel(self.ponto2dxf)
        self.label_25.setGeometry(QtCore.QRect(240, 160, 81, 20))
        self.label_25.setObjectName("label_25")
        self.pushButton_salvaPontos2dxf = QtWidgets.QPushButton(self.ponto2dxf)
        self.pushButton_salvaPontos2dxf.setGeometry(QtCore.QRect(278, 516, 121, 30))
        self.pushButton_salvaPontos2dxf.setObjectName("pushButton_salvaPontos2dxf")
        self.groupBox = QtWidgets.QGroupBox(self.ponto2dxf)
        self.groupBox.setGeometry(QtCore.QRect(528, 488, 275, 93))
        self.groupBox.setObjectName("groupBox")
        self.radioButtonpontotodxf2d = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonpontotodxf2d.setGeometry(QtCore.QRect(44, 54, 103, 20))
        self.radioButtonpontotodxf2d.setObjectName("radioButtonpontotodxf2d")
        self.radioButtonponto2dxf3d = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonponto2dxf3d.setGeometry(QtCore.QRect(156, 54, 103, 20))
        self.radioButtonponto2dxf3d.setObjectName("radioButtonponto2dxf3d")
        self.pushButtonPontotoDXFReordenar = QtWidgets.QPushButton(self.ponto2dxf)
        self.pushButtonPontotoDXFReordenar.setGeometry(QtCore.QRect(814, 134, 145, 30))
        self.pushButtonPontotoDXFReordenar.setObjectName("pushButtonPontotoDXFReordenar")
        self.tabWidget.addTab(self.ponto2dxf, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TRANSCOOR"))
        self.comboEPSG_from.setItemText(0, _translate("Form", "32725 WGS 84 / UTM zone 25S "))
        self.comboEPSG_from.setItemText(1, _translate("Form", "4618    GCS SAD69"))
        self.comboEPSG_from.setItemText(2, _translate("Form", "3857             GOOGLE MAPS"))
        self.comboEPSG_from.setItemText(3, _translate("Form", "4674    GCS SIRGAS 2000"))
        self.comboEPSG_from.setItemText(4, _translate("Form", "4326    GCS WGS84"))
        self.comboEPSG_from.setItemText(5, _translate("Form", "22521    Corrego Alegre / UTM zone 21S"))
        self.comboEPSG_from.setItemText(6, _translate("Form", "22522    Corrego Alegre / UTM zone 22S"))
        self.comboEPSG_from.setItemText(7, _translate("Form", "22523    Corrego Alegre / UTM zone 23S"))
        self.comboEPSG_from.setItemText(8, _translate("Form", "22524    Corrego Alegre / UTM zone 24S"))
        self.comboEPSG_from.setItemText(9, _translate("Form", "22525    Corrego Alegre / UTM zone 25S"))
        self.comboEPSG_from.setItemText(10, _translate("Form", "29168    SAD69 / UTM zone 18N"))
        self.comboEPSG_from.setItemText(11, _translate("Form", "29188    SAD69 / UTM zone 18S"))
        self.comboEPSG_from.setItemText(12, _translate("Form", "29169    SAD69 / UTM zone 19N"))
        self.comboEPSG_from.setItemText(13, _translate("Form", "29189    SAD69 / UTM zone 19S"))
        self.comboEPSG_from.setItemText(14, _translate("Form", "29170    SAD69 / UTM zone 20N"))
        self.comboEPSG_from.setItemText(15, _translate("Form", "29190    SAD69 / UTM zone 20S"))
        self.comboEPSG_from.setItemText(16, _translate("Form", "29191    SAD69 / UTM zone 21S"))
        self.comboEPSG_from.setItemText(17, _translate("Form", "29192    SAD69 / UTM zone 22S"))
        self.comboEPSG_from.setItemText(18, _translate("Form", "29193    SAD69 / UTM zone 23S"))
        self.comboEPSG_from.setItemText(19, _translate("Form", "29194    SAD69 / UTM zone 24S"))
        self.comboEPSG_from.setItemText(20, _translate("Form", "29195    SAD69 / UTM zone 25S"))
        self.comboEPSG_from.setItemText(21, _translate("Form", "31972    SIRGAS 2000 / UTM zone 18N"))
        self.comboEPSG_from.setItemText(22, _translate("Form", "31978    SIRGAS 2000 / UTM zone 18S"))
        self.comboEPSG_from.setItemText(23, _translate("Form", "31973    SIRGAS 2000 / UTM zone 19N"))
        self.comboEPSG_from.setItemText(24, _translate("Form", "31979    SIRGAS 2000 / UTM zone 19S"))
        self.comboEPSG_from.setItemText(25, _translate("Form", "31974    SIRGAS 2000 / UTM zone 20N"))
        self.comboEPSG_from.setItemText(26, _translate("Form", "31980    SIRGAS 2000 / UTM zone 20S"))
        self.comboEPSG_from.setItemText(27, _translate("Form", "31981    SIRGAS 2000 / UTM zone 21S"))
        self.comboEPSG_from.setItemText(28, _translate("Form", "31982    SIRGAS 2000 / UTM zone 22S"))
        self.comboEPSG_from.setItemText(29, _translate("Form", "31983    SIRGAS 2000 / UTM zone 23S"))
        self.comboEPSG_from.setItemText(30, _translate("Form", "31984    SIRGAS 2000 / UTM zone 24S"))
        self.comboEPSG_from.setItemText(31, _translate("Form", "31985    SIRGAS 2000 / UTM zone 25S"))
        self.comboEPSG_from.setItemText(32, _translate("Form", "32618    WGS 84 / UTM zone 18N"))
        self.comboEPSG_from.setItemText(33, _translate("Form", "32718    WGS 84 / UTM zone 18S"))
        self.comboEPSG_from.setItemText(34, _translate("Form", "32619    WGS 84 / UTM zone 19N"))
        self.comboEPSG_from.setItemText(35, _translate("Form", "32719    WGS 84 / UTM zone 19S"))
        self.comboEPSG_from.setItemText(36, _translate("Form", "32620    WGS 84 / UTM zone 20N"))
        self.comboEPSG_from.setItemText(37, _translate("Form", "32720    WGS 84 / UTM zone 20S"))
        self.comboEPSG_from.setItemText(38, _translate("Form", "32721    WGS 84 / UTM zone 21S"))
        self.comboEPSG_from.setItemText(39, _translate("Form", "32722    WGS 84 / UTM zone 22S"))
        self.comboEPSG_from.setItemText(40, _translate("Form", "32723    WGS 84 / UTM zone 23S"))
        self.comboEPSG_from.setItemText(41, _translate("Form", "32724    WGS 84 / UTM zone 24S"))
        self.comboEPSG_from.setItemText(42, _translate("Form", "32725    WGS 84 / UTM zone 25S"))
        self.comboEPSG_to.setItemText(0, _translate("Form", " 32725 WGS 84 / UTM zone 25S "))
        self.comboEPSG_to.setItemText(1, _translate("Form", "4618    GCS SAD69"))
        self.comboEPSG_to.setItemText(2, _translate("Form", "3857             GOOGLE MAPS"))
        self.comboEPSG_to.setItemText(3, _translate("Form", "4674    GCS SIRGAS 2000"))
        self.comboEPSG_to.setItemText(4, _translate("Form", "4326    GCS WGS84"))
        self.comboEPSG_to.setItemText(5, _translate("Form", "22521    Corrego Alegre / UTM zone 21S"))
        self.comboEPSG_to.setItemText(6, _translate("Form", "22522    Corrego Alegre / UTM zone 22S"))
        self.comboEPSG_to.setItemText(7, _translate("Form", "22523    Corrego Alegre / UTM zone 23S"))
        self.comboEPSG_to.setItemText(8, _translate("Form", "22524    Corrego Alegre / UTM zone 24S"))
        self.comboEPSG_to.setItemText(9, _translate("Form", "22525    Corrego Alegre / UTM zone 25S"))
        self.comboEPSG_to.setItemText(10, _translate("Form", "29168    SAD69 / UTM zone 18N"))
        self.comboEPSG_to.setItemText(11, _translate("Form", "29188    SAD69 / UTM zone 18S"))
        self.comboEPSG_to.setItemText(12, _translate("Form", "29169    SAD69 / UTM zone 19N"))
        self.comboEPSG_to.setItemText(13, _translate("Form", "29189    SAD69 / UTM zone 19S"))
        self.comboEPSG_to.setItemText(14, _translate("Form", "29170    SAD69 / UTM zone 20N"))
        self.comboEPSG_to.setItemText(15, _translate("Form", "29190    SAD69 / UTM zone 20S"))
        self.comboEPSG_to.setItemText(16, _translate("Form", "29191    SAD69 / UTM zone 21S"))
        self.comboEPSG_to.setItemText(17, _translate("Form", "29192    SAD69 / UTM zone 22S"))
        self.comboEPSG_to.setItemText(18, _translate("Form", "29193    SAD69 / UTM zone 23S"))
        self.comboEPSG_to.setItemText(19, _translate("Form", "29194    SAD69 / UTM zone 24S"))
        self.comboEPSG_to.setItemText(20, _translate("Form", "29195    SAD69 / UTM zone 25S"))
        self.comboEPSG_to.setItemText(21, _translate("Form", "31972    SIRGAS 2000 / UTM zone 18N"))
        self.comboEPSG_to.setItemText(22, _translate("Form", "31978    SIRGAS 2000 / UTM zone 18S"))
        self.comboEPSG_to.setItemText(23, _translate("Form", "31973    SIRGAS 2000 / UTM zone 19N"))
        self.comboEPSG_to.setItemText(24, _translate("Form", "31979    SIRGAS 2000 / UTM zone 19S"))
        self.comboEPSG_to.setItemText(25, _translate("Form", "31974    SIRGAS 2000 / UTM zone 20N"))
        self.comboEPSG_to.setItemText(26, _translate("Form", "31980    SIRGAS 2000 / UTM zone 20S"))
        self.comboEPSG_to.setItemText(27, _translate("Form", "31981    SIRGAS 2000 / UTM zone 21S"))
        self.comboEPSG_to.setItemText(28, _translate("Form", "31982    SIRGAS 2000 / UTM zone 22S"))
        self.comboEPSG_to.setItemText(29, _translate("Form", "31983    SIRGAS 2000 / UTM zone 23S"))
        self.comboEPSG_to.setItemText(30, _translate("Form", "31984    SIRGAS 2000 / UTM zone 24S"))
        self.comboEPSG_to.setItemText(31, _translate("Form", "31985    SIRGAS 2000 / UTM zone 25S"))
        self.comboEPSG_to.setItemText(32, _translate("Form", "32618    WGS 84 / UTM zone 18N"))
        self.comboEPSG_to.setItemText(33, _translate("Form", "32718    WGS 84 / UTM zone 18S"))
        self.comboEPSG_to.setItemText(34, _translate("Form", "32619    WGS 84 / UTM zone 19N"))
        self.comboEPSG_to.setItemText(35, _translate("Form", "32719    WGS 84 / UTM zone 19S"))
        self.comboEPSG_to.setItemText(36, _translate("Form", "32620    WGS 84 / UTM zone 20N"))
        self.comboEPSG_to.setItemText(37, _translate("Form", "32720    WGS 84 / UTM zone 20S"))
        self.comboEPSG_to.setItemText(38, _translate("Form", "32721    WGS 84 / UTM zone 21S"))
        self.comboEPSG_to.setItemText(39, _translate("Form", "32722    WGS 84 / UTM zone 22S"))
        self.comboEPSG_to.setItemText(40, _translate("Form", "32723    WGS 84 / UTM zone 23S"))
        self.comboEPSG_to.setItemText(41, _translate("Form", "32724    WGS 84 / UTM zone 24S"))
        self.comboEPSG_to.setItemText(42, _translate("Form", "32725    WGS 84 / UTM zone 25S"))
        self.pushButton.setText(_translate("Form", "Abrir"))
        self.label.setText(_translate("Form", "EPSG DE ORIGEM"))
        self.label_2.setText(_translate("Form", "EPSG DE DESTINO"))
        self.lineY.setText(_translate("Form", "6997318.540"))
        self.lineX.setText(_translate("Form", "341486.093"))
        self.calculaButton.setText(_translate("Form", "Calcular"))
        self.label_3.setText(_translate("Form", "Programa desenvolvido por Thiago N. S. Igarashi - Engenheiro Cartógrafo e Agrimensor"))
        self.label_4.setText(_translate("Form", "N - Y - Lat"))
        self.label_5.setText(_translate("Form", "E - X - Lon"))
        self.invertButton.setText(_translate("Form", "Inverte"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Converte Coordenadas"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Cod"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Hz"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Vt"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(4)
        item.setText(_translate("Form", "di"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(5)
        item.setText(_translate("Form", "dh"))
        item = self.tableWidget_dadosBrutos.horizontalHeaderItem(6)
        item.setText(_translate("Form", "hs"))
        self.pushButton_openstation.setText(_translate("Form", "Abrir "))
        self.pushButton_Recalcula.setText(_translate("Form", "Calcular Hz"))
        self.pushButton_plota_pontos.setText(_translate("Form", "Plotar pontos"))
        item = self.tableWidget_coordenadasFinais.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget_coordenadasFinais.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Cod"))
        item = self.tableWidget_coordenadasFinais.horizontalHeaderItem(2)
        item.setText(_translate("Form", "N"))
        item = self.tableWidget_coordenadasFinais.horizontalHeaderItem(3)
        item.setText(_translate("Form", "E"))
        item = self.tableWidget_coordenadasFinais.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Z"))
        self.pushButton_salvarCoordenadas.setText(_translate("Form", "Salvar coordenadas"))
        self.lineEditEstacao_N.setText(_translate("Form", "10000"))
        self.lineEditEstacao_E.setText(_translate("Form", "5000"))
        self.lineEditEstacao_H.setText(_translate("Form", "100"))
        self.label_6.setText(_translate("Form", "N: "))
        self.label_7.setText(_translate("Form", "E:"))
        self.label_8.setText(_translate("Form", "H: "))
        self.label_9.setText(_translate("Form", "ESTAÇÃO"))
        self.label_10.setText(_translate("Form", "RÉ"))
        self.label_11.setText(_translate("Form", "N:"))
        self.label_12.setText(_translate("Form", "E:"))
        self.label_13.setText(_translate("Form", "H:"))
        self.pushButtonCalculaAzimute.setText(_translate("Form", "Calcula Azimute"))
        self.label_14.setText(_translate("Form", "TABELA DE DADOS BRUTOS - CADERNETA DE CAMPO"))
        self.label_15.setText(_translate("Form", "TABELA DE COORDENADAS FINAIS"))
        self.label_16.setText(_translate("Form", "AZIMUTE INICIAL:"))
        self.pushButton_exportar_dxf.setText(_translate("Form", "Exportar dxf"))
        self.pushButton_Teste.setText(_translate("Form", "Teste"))
        self.groupBoxXYouXYZ.setTitle(_translate("Form", "XY ou XYZ"))
        self.radioButton2D.setText(_translate("Form", "2D"))
        self.radioButton3D.setText(_translate("Form", "3D"))
        self.checkBoxCamadaMuro.setText(_translate("Form", "Camada"))
        self.checkBoxCamadaCota.setText(_translate("Form", "Camada"))
        self.label_26.setText(_translate("Form", "Desenvolvido por Thiago Igarashi - Engenheiro Cartógrafo e Agrimensor"))
        self.groupBoxQualoTipo.setTitle(_translate("Form", "Qual Tipo?"))
        self.radioButtonTopografica.setText(_translate("Form", "Topográfica"))
        self.radioButtonUTM.setText(_translate("Form", "UTM"))
        self.groupBoxQualoTipo_2.setTitle(_translate("Form", "Poligonal"))
        self.radioButtonTopografica_2.setText(_translate("Form", "Aberta"))
        self.radioButtonUTM_2.setText(_translate("Form", "Enquadrada"))
        self.radioButtonUTM_3.setText(_translate("Form", "Fechada"))
        self.pushButton_Virgual_Ponto_Change.setText(_translate("Form", ", ."))
        self.pushButton_Coordenada_Estacao.setText(_translate("Form", "AE"))
        self.pushButton_SalvaCoordenadaEstacao.setText(_translate("Form", "SE"))
        self.pushButton_DX_teste.setText(_translate("Form", "DX"))
        self.pushButton_RecalculaPor2pontos.setText(_translate("Form", "Calcular por 2pt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Topografia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Puissant"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Form", "NBR 14166"))
        self.pushButton_abrir_Conexao.setText(_translate("Form", "Abrir Conexão"))
        self.label_17.setText(_translate("Form", "Porta: "))
        self.label_18.setText(_translate("Form", "Bits por segundo:"))
        self.label_19.setText(_translate("Form", "Tamanho do dado:"))
        self.label_20.setText(_translate("Form", "Paridade:"))
        self.label_21.setText(_translate("Form", "Bits de Parada:"))
        self.label_22.setText(_translate("Form", "Controle de Fluxo"))
        self.label_status_conexao.setText(_translate("Form", "Status da Conexão: Off"))
        self.pushButton_localizaPorta.setText(_translate("Form", "Localiza Porta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Com. Serial"))
        self.pushButton_pontos2dxf.setText(_translate("Form", "Abrir "))
        self.label_23.setText(_translate("Form", "PONTOS PARA SEREM TRANSFORMADOS EM DXF"))
        item = self.tableWidget_dadosBrutos_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget_dadosBrutos_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Descricao"))
        item = self.tableWidget_dadosBrutos_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "X"))
        item = self.tableWidget_dadosBrutos_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Y"))
        item = self.tableWidget_dadosBrutos_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Z"))
        self.label_24.setText(_translate("Form", "PADRAO:"))
        self.label_25.setText(_translate("Form", "SEPARADOR:"))
        self.pushButton_salvaPontos2dxf.setText(_translate("Form", "Exportar para DXF"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.radioButtonpontotodxf2d.setText(_translate("Form", "2D"))
        self.radioButtonponto2dxf3d.setText(_translate("Form", "3D"))
        self.pushButtonPontotoDXFReordenar.setText(_translate("Form", "REORDENAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ponto2dxf), _translate("Form", "Pontos 2 dxf"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Qgis Plugins"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "ftp/ssh/scp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "Fotogrametria"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Form", "Resultado - Precisões"))
